name: Build and Publish Droidian Kernel

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "59 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Kernel Build and Upload"
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: droidian
    
    - name: Run build script
      run: ./build_droidian.sh
    
    - name: List generated files
      run: ls -la out/

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: droidian-deb-packages
        path: out/*.deb
        retention-days: 1
